
export const eras = [
  {
    id: "birth",
    name: "Birth of Mobile CPUs",
    period: "Mid-1990s – Early 2000s",
    accent: "#8888a0",
    summary:
      "Low-power RISC processors adapted from desktop/embedded designs, built to squeeze basic computing into battery-powered handsets.",
    chips: [
      {
        id: "arm7tdmi",
        name: "ARM7TDMI",
        year: 1994,
        cores: 1,
        clockGHz: 0.02,
        process: "600nm–350nm (varies by licensee)",
        transistors: "~74,000 (core only)",
        notable: "32-bit RISC core with Thumb 16-bit instruction mode for code density.",
        perfIndex: 1,
      },
      {
        id: "strongarm",
        name: "Intel StrongARM SA-1100",
        year: 1996,
        cores: 1,
        clockGHz: 0.206,
        process: "350nm",
        transistors: "~2.5 million",
        notable: "Licensed ARM design fabbed by Intel; powered early PDAs.",
        perfIndex: 2,
      },
      {
        id: "dragonball",
        name: "Motorola DragonBall EZ",
        year: 1999,
        cores: 1,
        clockGHz: 0.033,
        process: "350nm",
        transistors: "~1 million (est.)",
        notable: "68000-derived core used in early Palm devices.",
        perfIndex: 1.2,
      },
    ],
  },
  {
    id: "arm-revolution",
    name: "The ARM Revolution",
    period: "2007 – 2012",
    accent: "#00e5ff",
    summary:
      "The iPhone and Android eras arrive: ARM architecture becomes the default, and dedicated ISPs/DSPs start offloading media work from the CPU.",
    chips: [
      {
        id: "cortex-a8",
        name: "ARM Cortex-A8",
        year: 2007,
        cores: 1,
        clockGHz: 0.6,
        process: "65nm",
        transistors: "~110 million",
        notable: "First superscalar ARM core; basis for many early smartphone SoCs.",
        perfIndex: 4,
      },
      {
        id: "apple-a4",
        name: "Apple A4",
        year: 2010,
        cores: 1,
        clockGHz: 1.0,
        process: "45nm",
        transistors: "~140 million (est.)",
        notable: "Apple's first in-house SoC, debuted in the iPad and iPhone 4.",
        perfIndex: 5,
      },
      {
        id: "snapdragon-s1",
        name: "Qualcomm Snapdragon S1 (QSD8250)",
        year: 2008,
        cores: 1,
        clockGHz: 1.0,
        process: "65nm",
        transistors: "~unknown (not widely published)",
        notable: "Scorpion CPU core with integrated GPU/modem for early Android phones.",
        perfIndex: 5,
      },
    ],
  },
  {
    id: "multicore",
    name: "The Multicore Era",
    period: "2011 – 2014",
    accent: "#00c2e0",
    summary:
      "Dual- and quad-core designs arrive to handle heavier multitasking and richer apps, trading battery headroom for parallel throughput.",
    chips: [
      {
        id: "tegra2",
        name: "NVIDIA Tegra 2",
        year: 2011,
        cores: 2,
        clockGHz: 1.0,
        process: "40nm",
        transistors: "~unknown (not widely published)",
        notable: "One of the first dual-core mobile SoCs, lacked NEON support.",
        perfIndex: 9,
      },
      {
        id: "apple-a6",
        name: "Apple A6",
        year: 2012,
        cores: 2,
        clockGHz: 1.3,
        process: "32nm",
        transistors: "~unknown (not widely published)",
        notable: "First Apple-designed (not just licensed) CPU core, \"Swift\".",
        perfIndex: 13,
      },
      {
        id: "snapdragon-600",
        name: "Qualcomm Snapdragon 600",
        year: 2013,
        cores: 4,
        clockGHz: 1.9,
        process: "28nm",
        transistors: "~unknown (not widely published)",
        notable: "Quad-core Krait 300 cores; flagship Android silicon of 2013.",
        perfIndex: 18,
      },
    ],
  },
  {
    id: "soc",
    name: "The System-on-Chip Era",
    period: "2015 – 2020",
    accent: "#7b61ff",
    summary:
      "CPU, GPU, modem, and memory converge on one die. big.LITTLE heterogeneous core pairing lets phones balance performance against battery life.",
    chips: [
      {
        id: "apple-a9",
        name: "Apple A9",
        year: 2015,
        cores: 2,
        clockGHz: 1.85,
        process: "14/16nm (dual-sourced)",
        transistors: "~2.0 billion",
        notable: "Dual-sourced from Samsung and TSMC; twin-core \"Twister\" design.",
        perfIndex: 28,
      },
      {
        id: "snapdragon-820",
        name: "Qualcomm Snapdragon 820",
        year: 2016,
        cores: 4,
        clockGHz: 2.15,
        process: "14nm",
        transistors: "~unknown (not widely published)",
        notable: "Custom Kryo cores, first Qualcomm design after Krait.",
        perfIndex: 30,
      },
      {
        id: "exynos-8890",
        name: "Samsung Exynos 8890",
        year: 2016,
        cores: 8,
        clockGHz: 2.3,
        process: "14nm",
        transistors: "~unknown (not widely published)",
        notable: "First Samsung custom \"Mongoose\" core, big.LITTLE octa-core.",
        perfIndex: 31,
      },
    ],
  },
  {
    id: "ai-efficiency",
    name: "The AI & Efficiency Era",
    period: "2021 – Present",
    accent: "#ff6ad5",
    summary:
      "Dedicated NPUs bring on-device machine learning, while 3nm/4nm process nodes push performance-per-watt further than ever.",
    chips: [
      {
        id: "a17-pro",
        name: "Apple A17 Pro",
        year: 2023,
        cores: 6,
        clockGHz: 3.78,
        process: "3nm (TSMC N3B)",
        transistors: "~19 billion",
        notable: "First 3nm smartphone chip; 16-core Neural Engine.",
        perfIndex: 95,
      },
      {
        id: "snapdragon-8g3",
        name: "Qualcomm Snapdragon 8 Gen 3",
        year: 2023,
        cores: 8,
        clockGHz: 3.3,
        process: "4nm (TSMC N4P)",
        transistors: "~unknown (not widely published)",
        notable: "Dedicated Hexagon NPU tuned for on-device generative AI.",
        perfIndex: 92,
      },
      {
        id: "dimensity-9300",
        name: "MediaTek Dimensity 9300",
        year: 2023,
        cores: 8,
        clockGHz: 3.25,
        process: "4nm (TSMC N4P)",
        transistors: "~unknown (not widely published)",
        notable: "All-big-core design (no efficiency-only cores) for sustained performance.",
        perfIndex: 90,
      },
    ],
  },
];

export const eraById = Object.fromEntries(eras.map((e) => [e.id, e]));